server:
  port: 18089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/visitor-system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    jedis:
      pool:
        max-active: 100
        max-idle: 20
        max-wait: 10000
        min-idle: 0
    password: ''
    port: 6379
    timeout: 3000
mybatis:
  mapper-locations: classpath:/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰
    #配置日志